import type { Metadata } from "next";
import localFont from 'next/font/local'
import { Collapse, Navbar } from "@/components";
import "./globals.css";
import { NavLinkHome } from "@/interfaces";

export const metadata: Metadata = {
  title: "Mercedes Costal",
  description: "Generated by create next app",
};

const gillSans = localFont({
  src: [
    {
      path: '../assets/fonts/Gill_Sans_Light.otf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../assets/fonts/Gill_Sans.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../assets/fonts/Gill_Sans_Medium.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../assets/fonts/Gill_Sans_Bold.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../assets/fonts/Gill_Sans_Heavy.otf',
      weight: '900',
      style: 'normal',
    },
  ],
  variable: '--gillsans'
});

const truetypewritter = localFont({
  src: '../assets/fonts/True_Typewritter.woff2',
  display: 'auto',
  variable: '--truetypewritter'
})

const links:Array<NavLinkHome> = [
  {
      title:'Wallpapers',
      links: [
          {
              title:'Murales',
              href:'/murals'
          },
          {
              title:'Patrones',
              href:'/patterns'
          },
          {
              title:'Cotizá',
              href:'/quote'
          },
      ]
  },
  {
      title:'Studio',
      links: [
          {
              title:'Meet the makers',
              href:'/meet-the-makers'
          },
          {
              title:'Puntos de venta',
              href:'/'
          },
      ]
  },
  {
      title:'Highlights',
      links: [
          {
              title:'Buen diseño',
              href:'/highlights/good-design'
          },
          {
              title:'Ateneo Splendid',
              href:'/highlights/ateneo-splendid'
          },
          {
              title:'UK',
              href:'/highlights/london-design-festival'
          },
          {
              title:'Manantiales Popup',
              href:'/highlights/manantiales-popup'
          },
          {
              title:'Feria Habitat Valencia',
              href:'/highlights/feria-habitat-valencia'
          },
      ]
  },
  {
      title:'MC Universe',
      links: [
          {
              title:'Fragrances',
              href:'/mc-universe/fragrances'
          },
          {
              title:'Our Book',
              href:'/mc-universe/our-book'
          },
          {
              title:'Costal Café',
              href:'/'
          },
      ]
  },
  {
      title:'Contact',
      links: [
          {
              title:'Trabaja con nosotros',
              href:'/contact'
          },
          {
              title:'Vende M.C.',
              href:'/contact'
          },
      ]
  },
];

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="es">
      <body className={`${gillSans.className} ${gillSans.variable} ${truetypewritter.variable} w-full min-h-svh flex flex-col items-center`}>
        <Navbar links={links}/>
        <Collapse links={links}/>
        {children}
      </body>
    </html>
  );
}