import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="es">
      <body className='font-gill-sans w-full min-h-svh flex flex-col items-center'>
        {children}
      </body>
    </html>
  );
}