import type { Metadata } from "next";
import localFont from 'next/font/local'
import { Navbar } from "@/components";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const gillSans = localFont({
  src: [
    {
      path: '../assets/fonts/Gill_Sans_Light.otf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../assets/fonts/Gill_Sans.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../assets/fonts/Gill_Sans_Medium.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../assets/fonts/Gill_Sans_Bold.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../assets/fonts/Gill_Sans_Heavy.otf',
      weight: '900',
      style: 'normal',
    },
  ],
});

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="es">
      <body className={`${gillSans.className} w-full min-h-svh flex flex-col items-center`}>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}